### ISSUE TITLE
AudioWorklet

### ISSUE THREAD

**Issue by macduff111** [charlieroberts/genish.js#8] opened 2018-01-31 23:04 UTC
Hi

Have you tried, or are planning to try, using genish with AudioWorklets? I'm using genish for a project and have it working well inside a ScriptProcessorNode. However, I get audio glitching for obvious reasons if I do any graphics stuff on the main thread as well. 

I've tried myself, but quickly got stuck with trying to setup genish within the AudioWorklet scope. I get errors if I try loading gen.lib.js into the AudioWorkletGlobalScope using audioContext.audioWorklet.addModule. I suspect it's to do with the way you have genish packaged, but I'm not that familiar with such techniques, and it's hard to unpick exactly what's going on in that file!

Any help or pointers would be much appreciated, as it's a great project and I'd love to keep using it.

**Comment by charlieroberts** [comment] 2018-01-31 23:33
Yes, I definitely want it to work with audioworklets! I'm hoping it won't be that painful. My idea is to compile the callback function outside the worklet and then pass in the result. This will take some changes to the underlying codegen functions.

I have some time this weekend I can devote to this and I've been meaning to look at it for a while... I'll let you know how it goes. I will be happy to leave the world of ScriptProcessor nodes behind :)

**Comment by macduff111** [comment] 2018-02-02 19:24
Great! 

> My idea is to compile the callback function outside the worklet and then pass in the result

I've tried something similar already, but came up against the limitation that you can't pass functions from the audioworklet node in the main scope to the audioworklet processor running on the audio thread. Communication between the two is via MessagePort which is limited to passing basic data types, or types that support the Transferable interface, which, as I understand it, is limited to buffers and bitmaps. 

I therefore thought of passing the callback as text and reconstructing it using eval, which is when I ran up against the issue of importing gen() into the processor scope. 

I hope you get further than me! I'm also around this weekend if you want to share any thoughts or problems...

**Comment by abramhindle** [comment] 2018-02-02 19:34
If you leave everything in the audioworklet thread (all of gibber) then you'll be fine, compile within the worklet would probably work so you're really just communicating what's getting analyzed or compiled. So you could send it source code.

**Comment by macduff111** [comment] 2018-02-02 21:23
@abramhindle @charlieroberts thanks for the encouragement - I'll give it another go...

**Comment by charlieroberts** [comment] 2018-02-02 21:52
@macduff111 actually, if you have a fork where I can see what you've tried that would probably be super helpful for me to get started with this.

**Comment by macduff111** [comment] 2018-02-02 22:56
No fork I'm afraid. I'm just importing gen.lib.js into my project.

All I've done is set up a simple AudioWorkletNode/Processor pair according to this:

https://developers.google.com/web/updates/2017/12/audio-worklet

then passed a text version of the genish callback from the node to the processor using postMessage / onmessage. The idea is to then eval the callback, and call it to service the process method of the Processor

The problems I hit are:

1) if I try to eval the passed function, it is trying to access gen.memory, which doesn't exist so...

2) if I then try importing gen.lib.js into the AudioWorkletProcessor I get the error

`_prelude.js:1 Uncaught (in promise) TypeError: Cannot set property 'genish' of undefined
    at _prelude.js:1 `

Hope that helps!

**Comment by charlieroberts** [comment] 2018-02-03 05:15
@macduf111 What if I did something like this:

```js
/* 
codegen for the genish graph:
     mul( noise(), .1 )
*/

class NoiseGenerator extends AudioWorkletProcessor {
  constructor( options ) {
    super( options )
    this.memory = new Float64Array(4096)
    this.noise  = Math.random
    
    // perform any other needed memory initialization here...
  }

  process( inputs, outputs, parameters ) {
    const output = outputs[0]
    const memory = this.memory
    const left   = output[ 0 ]
    const right  = output[ 1 ]
    
    for( let idx = 0; idx < left.length; ++idx ) {
      var noise0 = this.noise()
      var mul1 = noise0 * 0.1
      left[ idx ] = right[ idx ] = mul1
    }

    return true
  }
}
```

The challenges I see are primarily related to getting the memory initialized correctly, but I don't think this would be all that bad to implement. I'd also have to figure out how to deal with loading data in at a later point in time... primarily for loading audio files. This seems like it could actually be a big problem due to the death of SharedArrayBuffers thanks to spectre (https://www.mozilla.org/en-US/security/advisories/mfsa2018-01/).

**Comment by macduff111** [comment] 2018-02-03 12:23
> What if I did something like this:

where would you run the codegen? Node or processor side?

In my project I have an event sequencer, currently running in the scriptnode at audio sample rate, which dynamically calls genish callbacks for each event. So I don't think what you suggest would work for me: I need a single Processor where I can determine which of a list of precomputed callbacks I call at any given sample. 

For passing audio across, could this be done using the message port to transfer an ArrayBuffer?

https://developer.mozilla.org/en-US/docs/Web/API/Transferable

**Comment by charlieroberts** [comment] 2018-02-03 15:34
Codegen would happen in the node. In your specific case I think you'd have to write the codegen yourself unfortunately. Something like:

```js
// one block of memory to share between ugens
const mem = MemoryHelper.create( 4096, Float64Array )
const cb1 = gen.createCallback( noise(), mem )
const cb2 = gen.createCallback( cycle(220), mem )
const cb3 = gen.createCallback( phasor( .0001, 0, { min:0, max:1 } ), mem )

const workletCode = `
class NoiseGenerator extends AudioWorkletProcessor {
  constructor( options ) {
    super( options )
    this.memory = new Float64Array(4096)
    this.noise  = Math.random
    
    this.cb1 = ${cb1.toString()}
    
    this.cb2 = ${cb2.toString()}
      
    this.cb3 = ${cb3.toString()}      
  }


  process( inputs, outputs, parameters ) {
    const output = outputs[0]
    const memory = this.memory
    const left   = output[ 0 ]
    const right  = output[ 1 ]
    
    for( let idx = 0; idx < left.length; ++idx ) {
      let out = this.cb3() > .5 ? this.cb1() : this.cb2()
      
      left[ idx ] = right[ idx ] = out
    }

    return true
  }
}`
```
You could almost get away with doing this now with a bit of regex work to replace the string `gen` with `this` wherever you find it... except for the memory passing problem.  MessagePorts weren't implemented in AudioWorklets when I first played around with them so I can't say for sure... but yeah, ideally they should be a good solution for this!

Also, did you try the [ifelse ugen](http://www.charlie-roberts.com/genish/docs/index.html#routing-ifelse)? It's probably the most error-prone ugen in genish but it was designed for this type of use case.

**Comment by charlieroberts** [comment] 2018-02-03 18:28
OK, here's a start! https://github.com/charlieroberts/genish.js/tree/worklet

It currently only works with graphs that don't write to memory during codegen. Typically, the codegen stage also writes to memory to store initial values for ugens... since memory is initially zeroed out, any ugen with an initial value of 0 should work as intended. There are other situations that will break it, for example the `cycle` ugen generates a wavetable and stores it in memory the first time a `cycle` is instantiated, so that ugen won't work as it currently stands. Anyways, it's a start. Here's a couple of working examples (for the playground):

```js
play( mul( noise(), .1 ), 'noise' )

graph = phasor(
  add( 220, mul( phasor( 2 ), 110 ) ) 
)
  
play( graph, 'phasor' )
```

Note that  you can only register one worklet for a given name on a given audio context. So if you try to repeatedly modify/execute the code above, you have to also change the names of the generated processors (the second argument to play).

I'll keep making commits as I make progress, but I'm happy to report that the first part was fairly painless... took about 45 minutes to implement the changes!

**Comment by charlieroberts** [comment] 2018-02-03 19:15
OK, the memory instantiated during codegen is now automatically passed/assigned via MessagePort when the worklet is instantiated, which seems to magically solve most problems. Loading files seems to work fine... the amen break example works great (if you comment out the GUI code which doesn't work yet). 

Next problem is figuring out interaction... ideally every `param` ugen would generate an AudioParam on the associated worklet, so that its value could be controlled with regular getters / setters but also patched into by other WebAudio API nodes (including other worklets created with genish).

**Comment by macduff111** [comment] 2018-02-03 21:39
This is all really helpful - thanks. Going through your code changes is v instructive. I'll see if I can translate what you're doing into in my project...

**Comment by macduff111** [comment] 2018-02-03 22:49
Progress - hurrah! I managed to pass your rewritten codegen of a simple graph as text, plus gen.memory.heap to my worklet, and then reconstitute the callback with eval, and it works!

Next up I tried a more complex graph - one I'd got gibberish to generate (Karplus Strong). This almost worked - the callback contained a single reference to gen (a gen.exp call) which it choked on. I can see that you've changed gen.exp so I don't understand what's happened there. Any ideas?

**Comment by macduff111** [comment] 2018-02-03 23:03
If I replace gen.exp with Math.exp it then chokes on this.noise, but if I replace that with math.random, it works!
Is it the case that I'll have to add in all the maths functions as members of my AudioWorkletProcessor class?

**Comment by charlieroberts** [comment] 2018-02-03 23:10
give me a few minutes; I have a commit that fixes this. The problem is that t60 directly calls `gen.exp` in its codegen snippet. Actually, if you just want to change that one line in t60 to match the behavior in the other math functions (use `${ref}` instead of `gen` or `this`) it shouldn't be too hard a fix.

**Comment by charlieroberts** [comment] 2018-02-03 23:40
OK, should be fixed now. I'm also almost finished with handling params... the very last thing to take care of would be handling input from other WebAudio API ugens. I'm pretty happy... looks like this will get "finished" tonight!

**Comment by charlieroberts** [comment] 2018-02-04 00:14
Here's how I am handling `param` ugens, which provide controls from outside the graph. Unfortunately, (but probably to be expected) calls to generate AudioWorklet nodes are asynchronous, so I have to return a Promise from methods like `play` to be able to control the resulting node. Every `param` becomes an AudioParam object from the WebAudio API; you can access them as follows (if you're in the playground):

```js
nodePromise = play( cycle( param( 'freq', 330, 55, 2000 ) ) )

nodePromise.then( node => {
  // standard API accessor
  node.parameters.get( 'freq' ).value = 550 

  // genish sugar
  node.freq.value = 440
})
```

I changed the [theremin example in the playground](https://github.com/charlieroberts/genish.js/blob/worklet/playground/examples/thereminish_worklet.js) to add interactivity using the Promise returned by play as another example.

**Comment by charlieroberts** [comment] 2018-02-04 03:26
OK, that's it! You can now freely route WAAPI nodes into inputs of the generated audio worklets (using the `input()` ugen). @macduff111 I added a standalone (not in the playground) [example of this](https://github.com/charlieroberts/genish.js/blob/worklet/examples/sine_worklet.htm). Hopefully that will give you enough to keep moving forward.

**Comment by charlieroberts** [comment] 2018-02-04 07:18
Live versions:

[playground](https://node.charlieroberts.cricket/playground)
[standalone demo](https://node.charlieroberts.cricket/examples/sine_worklet.html)

**Comment by charlieroberts** [comment] 2018-02-04 20:54
I went through and ensured that all the demos in the playground worked, fixing bugs / solving problems along the way. Everything seems good now. @macduff111 I was wrong about fixing `t60` before, but it's fixed now and the Karplus-Strong example works as expected (you can try it out on the playground linked above). 

I'm going to go ahead and close this issue, but feel free to leave more comments here or start another issue if you find any bugs in the implementation. Thanks for motivating me to finally do this!

**Closed by charlieroberts** 2018-02-04 20:54 UTC

**Comment by macduff111** [comment] 2018-02-04 22:30
That's great. Again, many thanks. I'm pleased I provided the motivation!

In case you're curious, the project I'm working on is a mash-up / port to the browser of some iOS apps I wrote a while back - http://jonathanmackenzie.net/apps/index.html 

Scriptsonic was an attempt at a kind of tactile live-coding environment using Javascript. For Ops
I used Paul Batchelor's Soundpipe which is a low-level, graph-based, sample accurate audio library written in C. I was therefore delighted to discover in genish something similar in Javascript. I make a lot of sounds with chaotic feedback loops, where sample accuracy is really important.

Will keep you posted of any developments / issues / ideas etc.

**Comment by charlieroberts** [comment] 2018-02-05 07:38
Ah, cool! I've definitely run across Scriptsonic before, and Ops looks great! Will have to give it a go. Nice to virtually meet you. I briefly met Paul a couple of years back, his work is fantastic. 

I will be super excited to see any chaotic feedback systems you might make with genish, and know some other people who would probably be interested in as well. Please do keep me posted! Some cool examples to share could help spur some interest in the project...

**Comment by macduff111** [comment] 2018-02-05 20:25
Sure - I have a couple of systems I want to try porting to genish - I'll let you know
